### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by ghost** [ArkeologeN/pipl#2]
Hi when i use this library i get error callback is not a function this is my code. 
```
app.get('/pipl', function (req, res) {
    pipl.search.query('json', {"email": "hamzawaqas@live.com"}, function (err, data) {
        console.log(data);
    });
});
```
Any help please.

**Comment by ArkeologeN** [comment]
@Yaseenahmed402 It may not work because you're providing 3 arguments instead of two:

https://github.com/ArkeologeN/pipl/blob/master/lib/services/search.js#L13

Seems like you have to remove first argument?

**Comment by danazkari** [comment]
@ArkeologeN just run into this same issue, came to the issues in github looking for an answer and looks like I found it!

Now, would you consider adjusting the README to reflect your answer?
![image](https://cloud.githubusercontent.com/assets/349542/26749532/47f3be10-47ca-11e7-8173-a6291830ce9a.png)

I could help starting next week, since all my free time currently belongs to a project I'm working on, at least till next week :stuck_out_tongue:

**Comment by ArkeologeN** [comment]
@danazkari sound's good! can you please make a change and send a pull request? It would be great!

**Comment by danazkari** [comment]
Sure thing! I'll do it tonight!
